### ISSUE TITLE
2 Red errors on startup at main menu? Without any additional mods (Ideology+Biotech)

### ISSUE THREAD

**Issue by Danijongo** [SmArtKar/EnhancedBeliefs#3]
The following 2 red error log will appear whenever loading the mod at main menu, only mods loaded are Harmony & Hugslib (With Core, Ideology & Biotech enabled) NO ADDITIONAL ONES AT ALL

Here is full log: https://gist.github.com/HugsLibRecordKeeper/9cf0ad7112bfc001f6a8b4b136518932 
or [output_log.txt](https://github.com/SmArtKar/EnhancedBeliefs/files/15200883/output_log.txt)

[Enhanced Beliefs] Patch operation Verse.PatchOperationAdd(/Defs/TraderKindDef[defName="Empire_Caravan_TraderGeneral"]/stockGenerators) failed
file: F:\Steam\steamapps\workshop\content\294100\3233416451\1.5\Patches\Patches.xml
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.PatchOperation:Complete (string)
Verse.LoadedModManager:ClearCachedPatches ()
Verse.LoadedModManager:LoadAllActiveMods (bool)
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__28_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

=================

Could not resolve cross-reference to Verse.HediffDef named Inhumanized (wanter=nullifyingHediffs)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlCrossRefLoader:TryResolveDef<Verse.HediffDef> (string,Verse.FailMode,object)
Verse.DirectXmlCrossRefLoader/WantedRefForList`1<Verse.HediffDef>:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass16_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by SmArtKar** [comment]
Are you playing without Royalty DLC?

**Comment by SmArtKar** [comment]
Yeah, fix will be out shortly

**Comment by Danijongo** [comment]
> Are you playing without Royalty DLC?
Yep!

> Yeah, fix will be out shortly
Greatly appreciate it! That was impressively fast
Thank you :D
